### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by schmidsi** [stemmlerjs/khalilstemmler-blog#9]
I love your blog/website and wanted to subscribe to it via good ol' RSS feed because I believe in the open web. (Aside: This is a great reader app: https://ranchero.com/netnewswire/)

But it seems that the articles are not published as RSS. It shouldn't be that complicated. I will try to do it on a next.js app soon, but did not find time yet. Anyways, maybe you take the opportunity to do it with Gatsby and write an article about it?

**Comment by edzzn** [comment]
Found it! @schmidsi  https://khalilstemmler.com/rss.xml
